### ISSUE TITLE
Base protection

### ISSUE THREAD

**Issue by BurakDmb** [anar4732/OhmWars#5]
Pvpnin kapalı olduğu zamanlarda devreye girecek olan bu korumayı plugin ile yapmamız durumunda modlu eşyalar ile aşılabileceğini düşünmekteyim, bu korumayı sağlayabilmek için bir server modu yaratmamız gerekmektedir aksi takdirde ileride başımızı ağrıtacak bir konu haline gelecektir.

**Comment by anar4732** [comment]
- [ ] plugin testi yapılacak.
- [ ] duruma gör

**Comment by anar4732** [comment]
WorldGuardın koruma sistemi çok iyi yapılmış. (Factions bu sistemi kullanıyor). Modlu eşyalarla aşılmıyor. Testi yapılmıştır.
