### ISSUE TITLE
Gelir modeli

### ISSUE THREAD

**Issue by BurakDmb** [anar4732/OhmWars#7]
Sunucuya hepimiz saatlerimizi harcadık, gerektiğinde sabahladık. Bu emeklerimizin karşılığı olarak çok az miktarlarda para kazanmamız bu yaptığımız emeklerin bir hiç uğruna gitmesi anlamına gelir. Bu sebepten sunucudan aylık en az 200 lira kazanmamız gerektiğini düşünüyorum ki zaten bunun 50-100 lirasını oyuncu kazanabilmek için oyunculara hediye etmemiz gerekmekte. 

Bu paraları kazanabilmemiz için sunucuya bir gelir modeli oluşturmamız gerekmekte, bize para kazandırabilecek özellikler belirlemeliyiz. Ayrıca şuanda [MerAuth plugini](https://github.com/Nauza/MerAuth/releases) ile siteden bir şey alındığında oyunda eşya, perm verme işlemlerini otomatik yapabiliyoruz.

1-Takım kaptanlığı döneminde ohmwars marketinden para karşılığı kaptanlık satın alınabilmeli.
2-Oyun döneminde, para karşılığı maden oranı bir tık daha artmış mining world tahsil edilebilir.

Daha fazla gelir kazandıracak yol belirlenmesi gerekiyor.

Ekleme:

Kararlaştırılan gelir yöntemleri:

1. Para karşılığı satın alınabilen mining world(ore oranı normal dünyaya göre birazcık daha fazla ancak dengeyi etkilemeyecek düzeyde)
2. Oyuna kasa sistemi eklenecek, iki tip kasa olacak, birinci kasa tipini herkes elde edebilecek, anahtarı da normal craft edilebilecek, içerisinde hem çöp hemde güzel eşyalar çıkma şansı olacak ancak güzel eşya çıkma şansı oldukça az olacak. İkinci kasa tipi ise para ile satın alınabilecek, bu kasa tipinde güzel eşya çıkma şansı arttırılmış olacak.
3. Takım kaptanı olabilmek için para karşılığı başvuru sistemine girmeden kaptan olunabilecek. Bu kaptanlar bütün sunucu kurallarına tabi tutulup sadece kaptan seçimi olayından es geçmiş olacaklardır.

**Comment by anar4732** [comment]
2. seçenek olmusuz. PTW olmamalı sunucuda.

siteden bir şey alındıgında oyunda komutları uygulama işini nauza plugini halledemiyormu?
